### ISSUE TITLE
youtube downloader not found

### ISSUE THREAD

**Issue by VedantMadane** [Pavan4256/Python-Mini-Projects#1]
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
c:\users\admin\appdata\local\programs\python\python38-32\lib\site-packages\pafy\pafy.py in <module>
     47     try:
---> 48         import youtube_dl
     49         backend = "youtube-dl"

ModuleNotFoundError: No module named 'youtube_dl'

During handling of the above exception, another exception occurred:

ImportError                               Traceback (most recent call last)
<ipython-input-15-1c53f3445547> in <module>
----> 1 import pafy
      2 url="https://www.youtube.com/watch?v=UiBQ8eIPl_M"
      3 video=pafy.new(url)
      4 # get best resolution of the video
      5 best=video.getbest()

c:\users\admin\appdata\local\programs\python\python38-32\lib\site-packages\pafy\__init__.py in <module>
      5 
      6 # External api
----> 7 from .pafy import new
      8 from .pafy import set_api_key
      9 from .pafy import load_cache, dump_cache

c:\users\admin\appdata\local\programs\python\python38-32\lib\site-packages\pafy\pafy.py in <module>
     49         backend = "youtube-dl"
     50     except ImportError:
---> 51         raise ImportError(
     52                "pafy: youtube-dl not found; you can use the internal backend by "
     53                "setting the environmental variable PAFY_BACKEND to \"internal\". "

ImportError: pafy: youtube-dl not found; you can use the internal backend by setting the environmental variable PAFY_BACKEND to "internal". It is not enabled by default because it is not as well maintained as the youtube-dl backend.

**Comment by iamgpavan** [comment]
Download pafy module but using pip command
